language: c

env:
  global:
    secure: "SS5efj7kz0thoFmWqwrLwvXVvMMviJ2tKk+y0E6FyiVXZ173qRPn5ZGlIpLVVwx0pev1tf92+RQ/BmTha3lREf+qc9Gt9G3lBXzch4m5+gKAOG2XWvqSKnD2nVGBVjZvvC579Bt1JhFJ1bKMETGdJGOOCNU2+1TQlCfFhOPMCuORBD5m1N2kDWhGoDr8jhoV884gFeLYvSoQLbrXLo9IXVsj+KWI97Ck8SMCtT3oPc7jtqQrsZ4ECS5N+wXvR71HPpgP1lIe/K/wvvkLQmZvVWnVsroiiwGQbWKJuN0CcbG2ooxkzYT4BMbCoVdyezxFZNkyMQB7Adzgera+Cymh0zmQadK4SYuPR6wl+K9K8wgfGDikAw0dUyVnI2JjDvGjRq9IFy8nUfOK70OSP2OLG0FsSLCYENkm5+/iek41gEd7W0A7Kfz6n+4djGguqML8TJaKMY2qQ2so/hyE1Pv2ne2yHVNjXhDO0VBBgSULqRawWejNlvlubD0As9ea24CCgNYsiG9Zps7yERN14fL6to1u9pBxDxLyoqeqV2ngj5HTV9FAly6Q2lXUoqXjf+YTjkiFtNLFj6qSbHF2J/aGsuz+Cxn2fMB1Vh1LDTsQGPEaSF2GDg3CXOa9E8PXjRdLC2i0Aub+92yUdnARa54nhZ7nxF9Ly8lfc0STPMN3O7U="


notifications:
   email: 
      - lordrasmus@gmail.com


script:
#   - sudo apt-get install ${CC} ${CXX}
   - cmake .

compiler: gcc 
dist: focal

addons:
   apt:
      packages: ['cmake'] 

   
#jobs:
#   include:
      
#      
#   ##########################################################################################
#   #     Linux Test ( Coverity )                                                            #
#   ##########################################################################################
#
#    - os: linux
#      stage: linux
#      env: CC=gcc CXX=g++
#      addons:
#        apt:
#            packages: ['cmake']
#        coverity_scan:
#            project:
#                name: lordrasmus/p-net
#
#            notification_email: 
#                - lordrasmus@gmail.com
#
#            build_command: cmake .
#            branch_pattern: master
#
# 
     

    


