
env:
  global:
     - secure: "DnxBN1TkdYCYxbP3dr8sIoovmGbEr0FuFwtcvU9LDKXHteTb/GbnSrf9/RDbh8aZRtJmHGyMO3giQHjsy6q9gCMzOWfliP/rQIt6QeQq7WKNWTk3qcnWFjJW+3vlCVPPBEQJm0TNORjsBqMjs/4sED+JOliCAJIb9akORw99iNNSy0eHRsLFtv3Cu5l2KqE3l/q93Z5tzqrC/ern/oBWAbGT4Dg68fxQ7RFZPODRm/uqwL6Zh7KghTZrQU8E/SWauGEp6whAC6HB/i3dv6nkmunoyf/w0hKXmae4JC3hjjfDzHAnHzZwc9btTGAAOI6BISFLPERtRLZTYTtE5qISoVJ+h3HLee27CVo7T8XRikoMkEmEQRef3+eBQlA2CQpvwB/KaiCefoKUDdv26THYsG7DS56L1KWkyrLrLhPiG8rtdy0LfYsyO/gnio3LLhWIQ4jMP+WLjdzR0jLG/JLWzKjHjHuui8Bh2BRCNvpXNsK3//Axsl6Pydobr4ZNcC08Lm6RoLzxyeI13xZl2Vbs+K8PftsneEXSgGjZtYhKjEPL8DPNZ9asJ6TX99qQysu2fqgw5fIstJW3I1P1ZBYVUnRD6hYjWEZUMv+nRaezvx54JKzUYaq9oJP/IZDD72lQM5D4IO0gwyxvho3UOUxmQ8eKdDHVBcHKwYMUfVUdrBk="



notifications:
   email: 
      - lordrasmus@gmail.com


#script:
#   - sudo apt-get install ${CC} ${CXX}
#   - cmake .
#   - make pn_dev

#compiler: gcc 
dist: focal

addons:
   apt:
      packages: ['cmake'] 

#coverity_scan:
#   project:
#      name: lordrasmus/p-net

addons:
  coverity_scan:
    project:
      name: "lordrasmus/p-net"
    notification_email: lordrasmus@gmail.com
    build_command_prepend: cmake .
    build_command: make pn_dev
    branch_pattern: master
   
#jobs:
#   include:
      
#      
#   ##########################################################################################
#   #     Linux Test ( Coverity )                                                            #
#   ##########################################################################################
#
#    - os: linux
#      stage: linux
#      env: CC=gcc CXX=g++
#      addons:
#        apt:
#            packages: ['cmake']
#        coverity_scan:
#            project:
#                name: lordrasmus/p-net
#
#            notification_email: 
#                - lordrasmus@gmail.com
#
#            build_command: cmake .
#            branch_pattern: master
#
# 
     

    


